version: "3.8"

services:
  postgres:
    container_name: gestao_vagas_pg
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"  # Porta externa 5433, interna 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_vagas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
